### PR TITLE
Added background image to the login page

### LINKED ISSUE #2: add setting to allow background image to be set on login page
While custom css in most themes can be used to adjust the css on the page, adding images can be a bit harder - we should add the ability for an admin to upload an image to be used as a background image on the page within this plugins own settings.

### PR DESCRIPTION
**Pull request by sumaiyamannan**
Hi,

This will add setting to allow background image to be set on login page.

I was not able to use renderer for this as they were not giving me access to the #page-content div.

Regards,
Sumaiya

### CODE REVIEW

**Comment by danmarsden** [comment]
thanks Sumaiya - this feels a little strange - injecting the background image using js - can we do something similar to the way moodle core adds the background image to the page using css?

I note core themes use the *_get_extra_scss style functions to add to the header, but we should be able to use some process to add css to the custom login page to do it?

thanks!

**Comment by sumaiyamannan** [comment]
Hi Dan,
I have redone this via page renderer and output callback, I couldn't figure out through css or preprocessing. I have added an extra div to the page. I can work further to remove the div and add the bg to an existing div  but I would have to use js like used in local_catalyst plugin

**Comment by sumaiyamannan** [comment]
I have sorted this out in another branch, now it will add the background image without any callbacks and this branch has a clean history. https://github.com/catalyst/moodle-local_login/pull/8

**Comment by sumaiyamannan** [comment]
This is not needed anymore.

**Pull request closed without merging**
